name       : openjml-rac            # name of the package
version    : 1.8.19.20170726        # version of the package
kind       : tool                   # one of tool or spec(s)
description: The Runtime Assertion Checker for OpenJML.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


assumes:
  - cmd: java -version
    matches: java version "1.8.*
    message: "Please install Java 1.8 to use OpenJML."
    platform: all

depends:                               
  - package   : openjml
    version   : ">= 1.8.0 && < 1.9"
    platform  : all
