name       : openjml-rac            # name of the package
version    : 1.7.3.20150406-3       # version of the package
kind       : tool                   # one of tool or spec(s)
description: The Runtime Assertion Checker for OpenJML.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


assumes:
  - cmd: java -version
    matches: java version "1.7.*
    message: "Please install Java 1.7 to use OpenJML."
    platform: all

depends:                               
  - package   : openjml
    version   : ">= 1.7.3 && < 1.8"
    platform  : all
